project:
  type: website
  output-dir: docs
website:
  title: "Machine Learning blogs"
  description: "This is Akanksha Singh's personal blog"
  repo-url: https://akanksha7.github.io/MachineLearningBlogs/
  repo-actions: [source]
  navbar:
    right:
      - text: About
        href: about.qmd 
      - icon: github
        href: https://github.com/akanksha7
      - icon: linkedin
        href: https://www.linkedin.com/in/akanksha-singh-91b362112
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

