project:
  type: website
  output-dir: docs
website:
  title: "Akanksha Singh"
  description: "This is Akanksha Singh's personal blog"
  navbar:
    right:
      - text: About
        href: about.qmd 
      - icon: github
        href: https://github.com/akanksha7
      - icon: linkedin
        href: https://
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

